@startuml Use case ตู้หยอดน้ำ
rectangle ตู้หยอดน้ำ {
  (การหยอดน้ำ) .right.> (การแสดงผล) : include
  (การหยอดน้ำ) .up.> (การจัดการเงิน) : include
  (การหยอดน้ำ) .down.> (การจัดการเครื่องดื่ม) : include
}
(การหยอดน้ำ) -left- :ลูกค้า:
@enduml