@startuml
rectangle ตู้หยอดน้ำ {
  (การจัดการการเงิน) .right.> (การแสดงผล) : include
  (การจัดการเครื่องดื่ม) .up.> (การแสดงผล) : include
}
(การจัดการการเงิน) -left- :ลูกค้า:
(การจัดการเครื่องดื่ม) -left- :ลูกค้า:
@enduml