@startuml
actor "ลูกค้า"
participant "การจัดการการเงิน"
participant "การจัดการเครื่องดื่ม"
participant "การจัดการแสดงผล"

loop infinity
    "การจัดการการเงิน" -> "การจัดการแสดงผล" : แสดงคำยินตีตอนรับ()
    activate "การจัดการการเงิน"
    activate "การจัดการแสดงผล"
    "การจัดการแสดงผล" --> "ลูกค้า" : ยินดีต้อนรับสู่ตู้หยอดน้ำ
    deactivate "การจัดการแสดงผล"
    "ลูกค้า" -> "การจัดการการเงิน": หยอดเงิน(จำนวนเงิน)
    "การจัดการการเงิน" -> "การจัดการการเงิน" : บวกเพิ่มเงินหยอด(จำนวนเงิน)
    "การจัดการการเงิน" -> "การจัดการเครื่องดื่ม" : ตรวจสอบเครื่องดื่มที่ซื้อได้(จำนวนเงินหยอด)
    activate "การจัดการเครื่องดื่ม"
    "การจัดการเครื่องดื่ม" --> "การจัดการการเงิน" : [เครื่องดื่มที่ซื้อได้]
    deactivate "การจัดการเครื่องดื่ม"
    "การจัดการการเงิน" -> "การจัดการแสดงผล": แสดงยอดเงินกับเครื่องดื่ม(จำนวนเงินหยอด, [เครื่องดื่มที่ซื้อได้]) 
    activate "การจัดการแสดงผล"
    "การจัดการแสดงผล" --> "ลูกค้า" : จำนวนเงินหยอด, [เครื่องดื่มที่ซื้อได้]
    deactivate "การจัดการแสดงผล"
    "ลูกค้า" -> "การจัดการการเงิน" : เลือกเครื่องดื่ม(เครื่องดื่ม)
    "การจัดการการเงิน" -> "การจัดการการเงิน" : คำนวณเงินทอน(ราคาเครื่องดื่มที่เลือก)
    "การจัดการการเงิน" -> "การจัดการเครื่องดื่ม" : จ่ายเครื่องดื่ม(เครื่องดื่มที่เลือก)
    activate "การจัดการเครื่องดื่ม"
    "การจัดการเครื่องดื่ม" --> "ลูกค้า" : จ่ายเครื่องดื่ม
    deactivate "การจัดการเครื่องดื่ม"
    "การจัดการการเงิน" --> "ลูกค้า" : ทอนเงิน
    "การจัดการการเงิน" -> "การจัดการแสดงผล" : แสดงคำขอบคุณ(เครื่องดื่มที่เลือก)
    deactivate "การจัดการการเงิน"
    activate "การจัดการแสดงผล"
    "การจัดการแสดงผล" --> "ลูกค้า" : "ขอบคุณที่ซื้อเครื่องดื่มที่คุณเลือก" 
    deactivate "การจัดการแสดงผล"
end
@enduml