@startuml
start
if (เมื่อมีการหยอดเหรียญเข้าตู้) then (yes)
    :ตรวจสอบจำนวนเหรียญและชนิดของเหรียญ;
    :แสดงผลชนิดของน้ำที่สามารถเลือกซื้อได้;
    :ตรวจสอบจำนวนน้ำกระป๋องที่มีอยู่ในตู้;
    :รับผลการเลือกชนิดน้ำ;
    :ส่งน้ำที่เลือกออกมาจากช่อง;
    :จัดเก็บเงินข้ำระบบ;
    :หากมีเงินทอน ให้ทอนเงินที่เหลือ ที่ช่องรับเงินทอน;
else (no)
endif
end
@enduml