@startuml sequnce diagram เครื่องหยอดน้ำ
actor "ลูกค้า"
participant "การหยอดน้ำ"
participant "การจัดการการเงิน"
participant "การจัดการเครื่องดื่ม"


loop while loop infinity
    "การหยอดน้ำ" --> "ลูกค้า" : แสดง message ยินดีต้อนรับ
    activate "การหยอดน้ำ"
    "การหยอดน้ำ" -> "การจัดการเครื่องดื่ม" : ดึงข้อมูลเครื่องดื่มที่สามารถขายได้()
    activate "การจัดการเครื่องดื่ม"
    "การจัดการเครื่องดื่ม" --> "ลูกค้า" : แสดง message เครื่องดื่มที่ขายได้
    deactivate "การจัดการเครื่องดื่ม"
    "การหยอดน้ำ" -> "การจัดการการเงิน" : ดึงข้อมูลเงินที่ลูกค้าหยอด()
    activate "การจัดการการเงิน"
    "การจัดการการเงิน" --> "ลูกค้า" : แสดง message จำนวนเงินที่ลูกค้าหยอด
    "ลูกค้า" -> "การหยอดน้ำ": หยอดเงิน(จำนวนเงินหยอด)
    activate "ลูกค้า"
    alt กรณีหยอดเหรียญ 1 บาท 
        "การหยอดน้ำ" -> "การจัดการการเงิน" : กำหนคจำนวนเงินที่หยอด(จำนวนเงินเดิม+จำนวนเงินหยอด)
    else กรณีหยอดเหรียญ 2 บาท
        "การหยอดน้ำ" -> "การจัดการการเงิน" : กำหนคจำนวนเงินที่หยอด(จำนวนเงินเดิม+จำนวนเงินหยอด)
    else กรณีหยอดเหรียญ 5 บาท
        "การหยอดน้ำ" -> "การจัดการการเงิน" : กำหนคจำนวนเงินที่หยอด(จำนวนเงินเดิม+จำนวนเงินหยอด)
    else กรณีหยอดเหรียญ 10 บาท
        "การหยอดน้ำ" -> "การจัดการการเงิน" : กำหนคจำนวนเงินที่หยอด(จำนวนเงินเดิม+จำนวนเงินหยอด)
        deactivate "การจัดการการเงิน"
    else กรณีเลือก 0 เพื่อเลือกเครื่องดื่ม
        "การหยอดน้ำ" --> "ลูกค้า" : กรุณาพิมพ์ชื่อเครื่องดื่มที่ท่านต้องการ
        "ลูกค้า" -> "การหยอดน้ำ" : เลือกเครื่องดื่ม(ชื่อเครื่องดื่ม)
        loop for loop ของ drinkmanager.__drinklist
            alt ถ้าชื่อเครื่องดื่มตรงกับ drink obj ใน list อันไหนเป็นจริง
                alt ถ้าจำนวนเงินที่หยอด < ราคาของเครื่องดื่มที่ลูกค้าเลือกเป็นจริง
                    "การหยอดน้ำ" --> "ลูกค้า" : เงินที่หยอดนอ้ยกว่าราค่าสินค้ากรุณาหยอดใหม่
                else ถ้าจำนวนเงินที่หยอด < ราคาของเครื่องดื่มที่ลูกค้าเลือกเป็นเท็จ
                    "การหยอดน้ำ" -> "การหยอดน้ำ" : คำนวนเงินทอน = เงินหยอด - ราคาเครื่องดื่ม
                    "การหยอดน้ำ" -> "การจัดการการเงิน" : กำหนดเงินเก็นในตู้(เงินเก็บเดิม + ราคาเครื่องดื่ม)
                    activate "การจัดการการเงิน"
                    "การหยอดน้ำ" -> "การหยอดน้ำ" : ลดจำนวนเครื่องดื่ม 1 กระป๋อง
                    deactivate "การจัดการการเงิน"
                    "การหยอดน้ำ" -> "การจัดการการเงิน" : กำหนดให้เงินหยอดเท่ากับศูนย์(0)
                    activate "การจัดการการเงิน"
                    "การหยอดน้ำ" -> "การจัดการเครื่องดื่ม" : บันทึกจำนวนกระป๋องใหม่
                    deactivate "การจัดการการเงิน"
                    activate "การจัดการเครื่องดื่ม"
                    "การหยอดน้ำ" -> "การจัดการการเงิน" : บันทึกจำนวนเงินใหม่
                    deactivate "การจัดการเครื่องดื่ม"
                    activate "การจัดการการเงิน"
                    "การหยอดน้ำ" -> "การจัดการเครื่องดื่ม" : จ่ายเครื่องดื่ม(เครื่องดื่มที่จ่าย)
                    deactivate "การจัดการการเงิน"
                    activate "การจัดการเครื่องดื่ม"
                    "ลูกค้า" <-- "การจัดการเครื่องดื่ม" : แสดงเครื่องดื่มที่จ่าย
                    deactivate "การจัดการเครื่องดื่ม"
                    "การหยอดน้ำ" -> "การจัดการการเงิน" : จ่ายเงินทอน(จำนวนเงินทอนที่จ่าย)
                    activate "การจัดการการเงิน"
                    "ลูกค้า" <-- "การจัดการการเงิน" : แสดงเงินทอนที่จ่าย
                    deactivate "การจัดการการเงิน"
                end
                "การหยอดน้ำ" -> "การหยอดน้ำ" : break
            end
        end
    else กรณีอื่นๆ
        "การหยอดน้ำ" --> "ลูกค้า" : ท่านหยอดเงินผิดกรุณาหยอดใหม่ !!!        
    end
    
end
@enduml